### PR TITLE
`--force` option for proposal changes

### PR DESCRIPTION
**Pull request by Comeani**
This PR implements a "--force" option for both proposal creation and proposal date modification commands that are otherwise blocked due to overlapping date range with an extant proposal.
A warning is shown when these options are used. The default behavior is `force=False` when the flag is not supplied, and `--no-force` can be explicitly supplied. 

There are valid cases where users want to renew their SLURM allocation to be renewed prior to it's end date, and these changes will make that possible again.

If the active proposal/investment queries to the database return multiple proposals, the entries are sorted by descending start date, and the first is chosen. This should not cause any problems with proposals/investments with future start dates, as they do not register as active.

### CODE REVIEW

**Comment by Comeani** [comment]
```
(bank_deploy) [root@moss bank]# crc-bank proposal create mbarry --all-clusters 25000
Traceback (most recent call last):
  File "/ix/crc/nlc60/github/bank/bank_deploy/bin/crc-bank", line 8, in <module>
    sys.exit(CommandLineApplication.execute())
  File "/ix/crc/nlc60/github/bank/bank/cli/app.py", line 46, in execute
    executable(**cli_kwargs)
  File "/ix/crc/nlc60/github/bank/bank/account_logic.py", line 143, in create
    raise ProposalExistsError(f'Proposals for a given account cannot overlap: \n'
bank.exceptions.ProposalExistsError: Proposals for a given account cannot overlap: 
    existing range 2022-09-23 - 2023-09-23 
    provided range 2023-09-15 - 2024-09-15

(bank_deploy) [root@moss bank]# crc-bank account info mbarry
+----------------------------+---------------------------+----------------+
|     Proposal End Date:     |         09/23/2023        |                |
+----------------------------+---------------------------+----------------+
|        Proposal ID:        |             64            |                |
+----------------------------+---------------------------+----------------+
|                            |                           |                |
+----------------------------+---------------------------+----------------+
|        Cluster: SMP        |     Total SUs: 750000     |                |
+----------------------------+---------------------------+----------------+
|            User            |          SUs Used         |     % Used     |
+----------------------------+---------------------------+----------------+
|           cal211           |            1894           |      N/A       |
|           cdg52            |           14730           |       1        |
|           das333           |             0             |      N/A       |
|            mjd4            |            2404           |      N/A       |
|           mmb49            |             2             |      N/A       |
|           spr33            |            1975           |      N/A       |
+----------------------------+---------------------------+----------------+
|      Overall for SMP       |           21005           |       2        |
+----------------------------+---------------------------+----------------+
|                            |                           |                |
+----------------------------+---------------------------+----------------+
|        Floating SUs        |       SUs Remaining       |     % Used     |
+----------------------------+---------------------------+----------------+
|       *Floating SUs        |                           |                |
|       are applied on       |                           |                |
|       any cluster to       |             0*            |       0        |
|     cover usage above      |                           |                |
|         Total SUs          |                           |                |
+----------------------------+---------------------------+----------------+
|      Aggregate Usage       |             2             |                |
+----------------------------+---------------------------+----------------+

(bank_deploy) [root@moss bank]# crc-bank proposal create mbarry --all-clusters 25000 --force
/ix/crc/nlc60/github/bank/bank/account_logic.py:141: UserWarning: Creating the proposal despite overlap with an existing proposal
  warn("Creating the proposal despite overlap with an existing proposal")

(bank_deploy) [root@moss bank]# crc-bank account info mbarry
+----------------------------+-----------------------+----------------+
|     Proposal End Date:     |       09/15/2024      |                |
+----------------------------+-----------------------+----------------+
|        Proposal ID:        |          1986         |                |
+----------------------------+-----------------------+----------------+
|                            |                       |                |
+----------------------------+-----------------------+----------------+
|        Floating SUs        |     SUs Remaining     |     % Used     |
+----------------------------+-----------------------+----------------+
|       *Floating SUs        |                       |                |
|       are applied on       |                       |                |
|       any cluster to       |         25000*        |       0        |
|     cover usage above      |                       |                |
|         Total SUs          |                       |                |
+----------------------------+-----------------------+----------------+
|      Aggregate Usage       |           0           |                |
+----------------------------+-----------------------+----------------+

```
@chnixi Does this seem to be having the desired effect? It explains the overlap it found if `--force` is not provided, warns you if you do use force, and then establishes whatever is newly created as the active proposal similar to how renewals used to work.

**Comment by chnixi** [comment]
Looks good! Just two comments: 1. It would be good if the --force option is shown in the error message so the admin knows how to get around it. 2. Does this generalize to overlap for any cluster, or does one of the proposal have to be all-clusters?

**Comment by Comeani** [comment]
Just pushed a commit to add an item about the force flag to the error output:

```
(bank_deploy) [root@moss bank]# crc-bank proposal create test --all-clusters 25000 --start '06/06/2023'
Traceback (most recent call last):
  File "/ix/crc/nlc60/github/bank/bank_deploy/bin/crc-bank", line 8, in <module>
    sys.exit(CommandLineApplication.execute())
  File "/ix/crc/nlc60/github/bank/bank/cli/app.py", line 46, in execute
    executable(**cli_kwargs)
  File "/ix/crc/nlc60/github/bank/bank/account_logic.py", line 143, in create
    raise ProposalExistsError(f'By default, proposals for a given account cannot overlap: \n'
bank.exceptions.ProposalExistsError: By default, proposals for a given account cannot overlap: 
    existing range 2023-05-05 - 2024-05-04 
    provided range 2023-06-06 - 2024-06-06 
This can be overridden with the `--force` flag
(bank_deploy) [root@moss bank]# crc-bank proposal modify_date test --start '06/06/2023'
Traceback (most recent call last):
  File "/ix/crc/nlc60/github/bank/bank_deploy/bin/crc-bank", line 8, in <module>
    sys.exit(CommandLineApplication.execute())
  File "/ix/crc/nlc60/github/bank/bank/cli/app.py", line 46, in execute
    executable(**cli_kwargs)
  File "/ix/crc/nlc60/github/bank/bank/account_logic.py", line 246, in modify_date
    raise ProposalExistsError(f'By default, proposals for a given account cannot overlap: \n'
bank.exceptions.ProposalExistsError: By default, proposals for a given account cannot overlap: 
    existing range 2023-05-05 - 2024-05-04 
    provided range 2023-06-06 - 2024-05-04 
This can be overridden with the `--force` flag
```

**Comment by Comeani** [comment]
@chnixi Please see the above comment, and the overlap is calculated at the proposal start and end date level. 

The cluster level allocations (for 'all_clusters'/standard allocations or an individual cluster) are tied to a proposal, so the proposal's start and end date are their start and end date. Investment start and end dates are entirely separate. Does this help answer your question?

**Comment by chnixi** [comment]
> @chnixi Please see the above comment, and the overlap is calculated at the proposal start and end date level.
> 
> The cluster level allocations (for 'all_clusters'/standard allocations or an individual cluster) are tied to a proposal, so the proposal's start and end date are their start and end date. Investment start and end dates are entirely separate. Does this help answer your question?

OK, so the all-clusters option in the renewal command is just like an alias for standard/startup allocation, and there is no option for individual clusters such as -gpu, which is bound to a specific proposal? In that case it would make sense to rename the all-clusters flag to something like "startup" or "standard-proposal" so it's clear that the renewal command expects a proposal type as argument, not an enumeration of clusters.

**Comment by Comeani** [comment]
> > @chnixi Please see the above comment, and the overlap is calculated at the proposal start and end date level.
> > The cluster level allocations (for 'all_clusters'/standard allocations or an individual cluster) are tied to a proposal, so the proposal's start and end date are their start and end date. Investment start and end dates are entirely separate. Does this help answer your question?
> 
> OK, so the all-clusters option in the renewal command is just like an alias for standard/startup allocation, and there is no option for individual clusters such as -gpu, which is bound to a specific proposal? In that case it would make sense to rename the all-clusters flag to something like "startup" or "standard-proposal" so it's clear that the renewal command expects a proposal type as argument, not an enumeration of clusters.

Renewing is just creating a proposal to take the place of the existing proposal. `--all-clusters` is used to indicate how many SUs should be allocated to the floating service unit allocation.
```
(bank_deploy) [root@moss bank]# crc-bank proposal create --help
usage: crc-bank create [-h] [--start date] [--end date] [--force | --no-force] [--all-clusters su] [--smp su] [--mpi su] [--htc su] [--gpu su] [--teach su] [--invest su] account

positional arguments:
  account              the Slurm account name

optional arguments:
  -h, --help           show this help message and exit
  --start date         proposal start date (m/d/Y) - defaults to today
  --end date           proposal end date (m/d/Y) - defaults to 1 year from today
  --force, --no-force  boolean flag for whether or not to set the existing proposal to inactive and substitute a proposal with the provided values in it's place - default is False
  --all-clusters su    service units awarded across all clusters
  --smp su             service units awarded on the smp cluster
  --mpi su             service units awarded on the mpi cluster
  --htc su             service units awarded on the htc cluster
  --gpu su             service units awarded on the gpu cluster
  --teach su           service units awarded on the teach cluster
  --invest su          service units awarded on the invest cluster
```
The other cluster options are there, and and can be used to award SUs on the same proposal as a standard allocation, although usually we just overwrite instead of letting them live alongside eachother. There isn't really a distinction between proposal type, it's just a proposal that may or may not have an allocation of floating SUs.

**Comment by chnixi** [comment]
OK, everything looks good to go!

**Pull request merged**
